import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "A stylish cap designed for boys, perfect for casual outings and sun protection. Features a classic black and white color combination for versatile styling.",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "Tea Table",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "A sleek and modern tea table in a subtle gray finish. Ideal for living rooms, offering a spacious top for tea, snacks, or decorative items.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "High-quality, over-ear headphones providing excellent sound clarity and comfort. The mixed color design adds a touch of style while ensuring great performance.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Premium sunglasses with a sleek black design. Offers UV protection and a modern look, making it a must-have accessory for sunny days.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "A stylish and comfortable cap designed for boys. Perfect for outdoor activities and casual wear.",
  },
  {
    _id: 1002,
    img: spfTwo,
    productName: "Tea Table",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "A modern gray tea table, ideal for your living room or office space, combining both elegance and functionality.",
  },
  {
    _id: 1003,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "High-quality mixed-color headphones, offering excellent sound clarity for music lovers and gamers alike.",
  },
  {
    _id: 1004,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Stylish black sunglasses designed to protect your eyes from the sun while enhancing your look.",
  },
  {
    _id: 1005,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "A simple yet elegant flower base that adds charm to any room, perfect for displaying your favorite flowers.",
  },
  {
    _id: 1006,
    img: bestSellerTwo,
    productName: "New Backpack",
    price: "180.00",
    color: "Gray",
    badge: false,
    des: "A durable gray backpack, perfect for students or travelers who need a functional and stylish carrying solution.",
  },
  {
    _id: 1007,
    img: bestSellerThree,
    productName: "Household materials",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "A set of essential household materials to keep your home organized and efficient. Great for everyday use.",
  },
  {
    _id: 1008,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "A spacious black travel bag designed to carry all your essentials for a weekend getaway or longer trips.",
  },
  {
    _id: 1009,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "A sleek round clock with a modern black design, perfect for any desk or living room.",
  },
  {
    _id: 1010,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "A smart watch offering a variety of features such as fitness tracking, notifications, and more, in a stylish black design.",
  },
  {
    _id: 1011,
    img: newArrThree,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "A durable cloth basket designed for storing laundry, toys, or other household items. Its mixed colors make it both practical and decorative.",
  },
  {
    _id: 1012,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Colorful and entertaining toys designed to keep babies engaged and help with their development.",
  },
  {
    _id: 1013,
    img: newArrTwo,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "A stylish black smart watch packed with features to track your health, receive notifications, and more.",
  },

  {
    _id: 1014,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "A sleek black smart watch that tracks your fitness, monitors your heart rate, and connects to your phone for notifications.",
  },
  {
    _id: 1015,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Engaging and colorful toys designed to entertain babies and promote sensory development.",
  },
  {
    _id: 1016,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "A versatile smart watch offering customizable features, fitness tracking, and easy access to notifications.",
  },
  {
    _id: 1017,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "A spacious travel bag in black, designed for both short and long trips with multiple compartments for your essentials.",
  },
  {
    _id: 1018,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "A modern round table clock with a sleek black finish, perfect for any modern interior.",
  },
  {
    _id: 1019,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "A black smart watch with a sleek design, offering fitness tracking, notifications, and more.",
  },
  {
    _id: 1020,
    img: newArrThree,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "A multi-purpose cloth basket with a practical design for storing clothes, toys, or other household items.",
  },
  {
    _id: 1021,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "High-quality headphones that offer crisp sound and comfort, perfect for music lovers and casual listeners.",
  },
  {
    _id: 1022,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Protect your eyes from the sun's rays in style with these classic black sunglasses, offering both comfort and fashion.",
  },
  {
    _id: 1023,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "An elegant white and black flower base to enhance the beauty of your floral arrangements.",
  },
  {
    _id: 1024,
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "A fashionable and functional cap for boys, ideal for sunny days or casual outings.",
  },
  {
    _id: 1025,
    img: spfTwo,
    productName: "Tea Table",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "A sleek and stylish gray tea table that adds sophistication to any room.",
  },
  {
    _id: 1026,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Comfortable and durable mixed-color headphones that deliver high-quality sound.",
  },
  {
    _id: 1027,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Classic black sunglasses designed to keep your eyes safe and your look fashionable.",
  },
  {
    _id: 1028,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "A stylish and functional flower base to display your favorite blooms in any setting.",
  },
  {
    _id: 1029,
    img: bestSellerTwo,
    productName: "New Backpack",
    price: "180.00",
    color: "Gray",
    badge: false,
    des: "A gray backpack offering ample storage and comfort for everyday use or travel.",
  },
  {
    _id: 1030,
    img: bestSellerThree,
    productName: "Household materials",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Essential household materials to make your home life more organized and efficient.",
  },
  {
    _id: 1031,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "A durable and spacious black travel bag designed for convenience on the go.",
  },
  {
    _id: 1032,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "A stylish round clock with a modern design, perfect for decorating your home or office.",
  },
  {
    _id: 1033,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "A cutting-edge black smart watch that tracks your fitness, displays notifications, and more.",
  },
  {
    _id: 1034,
    img: newArrThree,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "A convenient and stylish cloth basket designed for organizing your household items.",
  },
  {
    _id: 1035,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Colorful and engaging toys designed to keep babies entertained while supporting their development.",
  },
  {
    _id: 1036,
    img: newArrTwo,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Vibrant and engaging, these funny toys are designed to captivate babies' attention and provide hours of amusement. Each toy is crafted to ensure safety and durability while promoting cognitive growth.",
  },
  {
    _id: 1037,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "This sleek black smart watch is not only stylish but also packed with features. It tracks fitness, provides notifications, and helps you stay connected. A perfect accessory for anyone on the go.",
  },
  {
    _id: 1038,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "A durable and spacious travel bag that makes packing easy. With multiple compartments for organization and a sleek black finish, it’s the perfect travel companion for business or leisure trips.",
  },
  {
    _id: 1039,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "This unique round table clock combines form and function. Its elegant black design fits seamlessly with any modern decor, while its clear display keeps you on time in style.",
  },
  {
    _id: 1040,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "This black smart watch is a blend of fashion and technology. It features advanced health tracking, customizable watch faces, and integrates seamlessly with your smartphone for calls and notifications.",
  },
  {
    _id: 1041,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "A versatile cloth basket that can hold laundry, toys, or other household items. Made from durable and washable fabric, it combines functionality with a stylish mixed color design.",
  },
  {
    _id: 1042,
    img: newArrThree,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "A versatile cloth basket that can hold laundry, toys, or other household items. Made from durable and washable fabric, it combines functionality with a stylish mixed color design.",
  },
  {
    _id: 1043,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "These mixed-color headphones provide excellent sound quality at an affordable price. Whether you're listening to music or attending a meeting, they ensure clear audio and comfort for extended wear.",
  },
  {
    _id: 1044,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "A pair of stylish black sunglasses that offer full UV protection. Designed for comfort and style, they are the perfect accessory for any sunny day outing.",
  },
  {
    _id: 1045,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "This elegant black and white flower base adds sophistication to any room. Perfect for displaying your favorite blooms, it’s a stylish and functional piece for your home decor.",
  },
  {
    _id: 1046,
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "A trendy cap designed for boys. Its black and white color scheme makes it versatile and stylish, while providing comfort and protection from the sun during outdoor activities.",
  },
];
// =================== PaginationItems End here =================
